modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "jei_attribute"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "jei_attribute.png"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.jei_attribute]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.jei_attribute]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.jei_attribute]]
modId = "jei"
mandatory = false
versionRange = "[15.0,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.jei_attribute]]
modId = "curios"
mandatory = false
versionRange = "[5.9,)"
ordering = "AFTER"
side = "BOTH"
